
                                       
								 ---[SQL CAPSTONE-2]---
								                                                            --PRESENTED BY,
																							       --J.CHARITHA.
--CREATING DATABASE NAME AS "STUDENT2"--
      CREATE DATABASE STUDENT2;
	
--USING WITH "STUDENT2"--
      USE STUDENT2;    

--CREATING 1ST TABLE NAME AS "STUDENT_INFO" AND ADDING CONSTRAINTS--
      CREATE TABLE STUDENT_INFO(
	                      STU_ID INT PRIMARY KEY,
						  STU_NAME VARCHAR(30) NOT NULL,
						  STU_CLASS CHAR(5) NOT NULL
						 ); 

--TO DELETE THE TABLE--
	  DROP TABLE STUDENT_INFO;	
			
--CREATING 2ND TABLE NAME AS "STUDENT_PERSONAL_INFO" AND ADDING CONSTRAINTS--
      CREATE TABLE STUDENT_PERSONAL_INFO(
	                                STU_ID INT PRIMARY KEY,
									STU_ADD VARCHAR(30) NOT NULL,
									STU_PHNO CHAR(14) UNIQUE
								   );
								   
--TO DROP THE TABLE--
	   DROP TABLE STUDENT_PERSONAL_INFO;
				
--CREATING 3RD TABLE NAME AS "STUDENT_MARKS" AND ADDING CONSTRAINS--	
       CREATE TABLE STUDENT_MARKS(
	                         STU_ID INT PRIMARY KEY,
							 STU_MATH_MARKS INT, 
							 STU_SCIENCE_MARKS INT,
							 STU_SOCIAL_MARKS INT,
							 STU_ENGLISH_MARKS INT
							);

--TO DROP THE TABLE--
	    DROP TABLE STUDENT_MARKS;	
			
--INSERTING SOME VALUES INTO 1ST TABLE "STUDENT_INFO"--
        INSERT INTO STUDENT_INFO VALUES(001,'KISHORE','5TH'),
		                               (002,'KUMARI','5TH'),
									   (003,'AKHITHA','4TH'),
									   (004,'CHARITHA','3RD'),
									   (005,'PAWAN','3RD'),
									   (006,'AYESH','4TH'),
									   (007,'SUMA','3RD'),
									   (008,'JHON','4TH'),
									   (009,'YESH','9TH'),
									   (010,'BALU','7TH');

--INSERTING SOME VALUES INTO 2ND TABLE "STUDENT_PERSNOL_INFO"--
        INSERT INTO STUDENT_PERSONAL_INFO VALUES(001,'VUY','9440592411'),
		                                        (002,'VUY','8143563139'),
												(003,'DUBAI','9182810198'),
												(004,'DUBAI','9398409095'),
												(005,'HYD','9553955681'),
												(006,'CHENNAI','9483672786'),
												(007,'MUMBAI','6301630522'),
												(008,'DELHI','9746251438'),
												(009,'PUNE','827367232'),
												(010,'CHENNAI','7902181895');

--INSERTING SOME VALUE SINTO 3RD TABLE "STUDENT_MARKS"--
        INSERT INTO STUDENT_MARKS VALUES(001,70,80,55,75),
		                                (002,59,60,45,55),
										(003,70,80,90,80),
										(004,45,50,55,35),
										(005,80,45,70,60),
										(006,30,40,30,45),
										(007,60,50,70,90),
										(008,35,43,50,50),
										(009,50,70,90,80),
										(010,80,50,90,60);

--TO DROP THE CONSTRAINTS--
--THIS IS FOR NOT NULL CONSTRAINTS--
          ALTER TABLE STUDENT_INFO
          ALTER COLUMN STU_CLASS CHAR(5);
-------
          ALTER TABLE STUDENT_PERSONAL_INFO
		  ALTER COLUMN STU_ADD VARCHAR(30);

--THIS IS FOR UNIQUE CONSTRAINT--		  
		  ALTER TABLE STUDENT_PERSONAL_INFO
		  DROP CONSTRAINT[UQ__STUDENT___695059DA41B824BC];
--FOR TABLE VIEW--
          SELECT * FROM STUDENT_INFO;

		  SELECT * FROM STUDENT_PERSONAL_INFO;

		  SELECT * FROM STUDENT_MARKS;


--TO VIEW WHO SCORED MORE THAN 60 MARKS IN ALL SUBJECTS AND ALSO VIWE THE PERSONAL INFO TABLE--
          SELECT * FROM STUDENT_PERSONAL_INFO
		  INNER JOIN STUDENT_MARKS
		  ON STUDENT_PERSONAL_INFO.STU_ID = STUDENT_MARKS.STU_ID
		  WHERE STU_MATH_MARKS>60 AND STU_SCIENCE_MARKS>60 AND STU_SOCIAL_MARKS>60 AND STU_ENGLISH_MARKS>60;


--TO CREATE PROCEDURE AND JOIN ALL TABLES TOGETHER--
         CREATE PROCEDURE TOPPER_STUDENTS
	     AS
	     BEGIN
           SELECT STU_NAME,STU_CLASS,STU_ADD,STU_PHNO,STU_MATH_MARKS,STU_SCIENCE_MARKS,STU_SOCIAL_MARKS,STU_ENGLISH_MARKS
		   FROM STUDENT_INFO
		   JOIN  STUDENT_PERSONAL_INFO
		   ON STUDENT_INFO.STU_ID = STUDENT_PERSONAL_INFO.STU_ID
		   JOIN STUDENT_MARKS
		   ON STUDENT_MARKS.STU_ID = STUDENT_INFO.STU_ID
		          WHERE STU_MATH_MARKS>60 AND STU_SCIENCE_MARKS>60 AND STU_SOCIAL_MARKS>60 AND STU_ENGLISH_MARKS>60
         END;
		 
--TO VIEW THE TABLE--
        TOPPER_STUDENTS;


--CREATING SIMPLE FUNCTION--
        CREATE FUNCTION STUDENT_PERCENTAGE(@MARKS INT)
		RETURNS TABLE
		AS
		RETURN
          (SELECT STU_ID, (STU_SCIENCE_MARKS*100)/100 AS 'PERCENTAGE' FROM STUDENT_MARKS);

--TO VIEW THE FUNCTION--
        SELECT*FROM DBO.STUDENT_PERCENTAGE(30);


 --TO CREATE TRANSACTION AND SAVE AS T1--
         BEGIN TRAN
	     BEGIN
	     SAVE TRAN T1
	        DELETE STUDENT_MARKS WHERE STU_MATH_MARKS<60 AND STU_ENGLISH_MARKS<60
		 END;

--TO VIEW FROM TABLE--
         SELECT * FROM STUDENT_MARKS;

--TO CREATE TRANSACTION ANS SAVE AS T2--
         BEGIN TRAN 
	     BEGIN
	     SAVE TRAN T2
	         DELETE STUDENT_MARKS WHERE STU_SCIENCE_MARKS<50 AND STU_SOCIAL_MARKS<50
		 END;

--TO VIEW FROM TABLE--
        SELECT * FROM STUDENT_MARKS;
 
--ROLLBACK TRANSACTION--
        ROLLBACK TRAN T1
	    ROLLBACK TRAN T2

--TO ROLLBACK WHOLE TRANSACTION--
        BEGIN TRAN
	    SAVE TRAN T1
	     DELETE STUDENT_MARKS WHERE STU_MATH_MARKS<60 AND STU_ENGLISH_MARKS<60;
		SAVE TRAN T2
	     DELETE STUDENT_MARKS WHERE STU_SCIENCE_MARKS<50 AND STU_SOCIAL_MARKS<50;
		 
    ROLLBACK 

--CREATE PROCEDURE TO DROP COLUMN--
           CREATE  PROCEDURE STUDENT_S
		   AS
		   BEGIN
		     SELECT STU_ID,STU_MATH_MARKS,STU_SCIENCE_MARKS FROM STUDENT_MARKS
          END;

--TO EXECUTE THE PROCEDURE--
		  EXEC STUDENT_S ALTER TABLE STUDENT_MARKS DROP COLUMN STU_SOCIAL_MARKS,STU_ENGLISH_MARKS

		  SELECT * FROM STUDENT_MARKS;

--ANOTHER MODEL TO DROP COLUMNS--
          CREATE  PROCEDURE STUDENT
		  AS
		  BEGIN
		      SELECT STU_ID,STU_MATH_MARKS,STU_ENGLISH_MARKS
			  FROM STUDENT_MARKS

			  ALTER TABLE STUDENT_MARKS
			  DROP COLUMN STU_SCIENCE_MARKS,STU_SOCIAL_MARKS
		 END;
		 
--TO EXECUTE THE PROCEDURE--
			EXEC STUDENT
--TO VIEW FROM TABLE--
			SELECT * FROM STUDENT_MARKS;    

----------------------------------------------------------< >--------------------------------------------------------------------
		                                            
													 --THANK:)YOU--


 CREATE OR ALTER PROCEDURE TABLEFILTER @TABLE_NAME VARCHAR(50), @COLUMN VARCHAR(100)
AS
BEGIN 

    DECLARE @TB_COL TABLE(COL VARCHAR(50))

    INSERT INTO @TB_COL(COL) (SELECT  COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @TABLE_NAME)

    DECLARE @COL_STR VARCHAR(100)

    SET @COL_STR = @COLUMN


    DECLARE @TEMP_STR VARCHAR(50)
    DECLARE @START_INDEX INT = 1
    DECLARE @TEMP_INDEX INT
    WHILE (SELECT LEN(@COL_STR)) <1
        BEGIN
            SET  @TEMP_INDEX = (CHARINDEX(',',@COL_STR)-1)
            SET @TEMP_STR =  (select SUBSTRING(@COL_STR,@START_INDEX,@TEMP_INDEX))
            PRINT @TEMP_STR
            DELETE FROM @TB_COL WHERE COL = @TEMP_STR
            SET @COL_STR = (SUBSTRING(@COL_STR,1,LEN(@COL_STR)))
            PRINT @COL_STR
        END
        PRINT @COL_STR
        SELECT * FROM @TB_COL
        PRINT('TEST2')
        DECLARE @T_STR VARCHAR(200) = ''
        WHILE( SELECT COUNT(*) FROM @TB_COL) <>0
            BEGIN
                SET @T_STR = @T_STR+','+(SELECT TOP(1)(COL) FROM @TB_COL)
                DELETE TOP(1) FROM @TB_COL
                SET @T_STR = (SELECT(SUBSTRING(@T_STR,2,LEN(@T_STR)-1)))
                PRINT @T_STR
            END


    PRINT('FINAL_TEST')
    PRINT(@T_STR)
    EXEC ('select ' + @T_STR + ' from' + ' '+ @TABLE_NAME)
END


TABLEFILTER'SALES_DATA','BRANCH,TIME,PAYMENT'
